import os
import re
import uuid
from typing import Dict, Tuple, Optional, List, Any
from dotenv import load_dotenv

# Project-specific imports
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))) # Add project root to sys.path

from logger_config import get_logger # Already configured by run_automation or main.py
from scraper.scraper import ScrapedIssue, load_issues_from_file
from github_handler.handler import GitHubHandler
from llm_handler.handler import LLMHandler, DEFAULT_PROMPT_TEMPLATE


logger = get_logger(__name__)

# --- Configuration Defaults ---
DEFAULT_ISSUES_FILE_PATH = "issues.json"
DEFAULT_BRANCH_PREFIX = "ai-solution/"
DEFAULT_PR_DISCLAIMER = "\n\n---\n*This pull request was generated by an AI assistant. Please review thoroughly before merging.*"


def parse_llm_solution(solution_text: str) -> Tuple[Optional[str], Optional[Dict[str, str]]]:
    """
    Parses the structured output from the LLMHandler.generate_solution method.

    The expected format includes an explanation followed by file changes:
    ---
    File: path/to/your/file.py
    ```python
    # Your code here
    ```
    ---
    (repeat for other files)

    Args:
        solution_text: The raw string output from the LLM.

    Returns:
        A tuple containing:
        - The explanation string (text before the first "--- File:").
        - A dictionary where keys are file paths and values are code/content blocks.
        Returns (None, None) if parsing fails or the format is incorrect.
    """
    if not solution_text:
        logger.error("LLM solution text is empty. Cannot parse.")
        return None, None

    logger.debug(f"Attempting to parse LLM solution. Length: {len(solution_text)} chars.")

    # Regex to find file blocks. This is a bit more robust.
    # It looks for "--- File: <path> ---" then captures content within ```<lang> ... ```
    # The (.*?) is non-greedy for the explanation part.
    # The re.DOTALL flag allows `.` to match newlines, crucial for multiline code blocks.

    # Split the text into explanation and file blocks part
    # The first "--- \nFile: " or "---File: " is the delimiter
    # Using a regex to find the first occurrence of the file marker
    first_file_marker_match = re.search(r"---\s*\n?File:", solution_text, re.IGNORECASE)

    if not first_file_marker_match:
        logger.warning("No '--- File:' markers found in LLM output. Treating entire output as explanation, no code changes.")
        # It's possible the LLM just gave an explanation without code, which might be valid.
        # Or, it failed to follow format. We'll return the text as explanation.
        return solution_text.strip(), {}

    explanation_end_index = first_file_marker_match.start()
    explanation = solution_text[:explanation_end_index].strip()
    code_section = solution_text[explanation_end_index:]

    file_changes: Dict[str, str] = {}

    # Regex to capture file path and code block
    # Pattern: --- File: <filepath> --- \n ```[optional language]\n <content> \n```
    # Making language optional and content capture robust
    pattern = re.compile(
        r"---\s*\n?File:\s*(?P<filepath>[^\n]+?)\s*---"  # File path line with optional newline after ---
        r"\s*\n?"                                       # Optional whitespace/newline
        r"```(?:[a-zA-Z0-9_.-]*)?\s*\n"                 # Code block start (optional language)
        r"(?P<content>.*?)\n"                           # Non-greedy content
        r"```",                                         # Code block end
        re.DOTALL | re.IGNORECASE
    )

    matches = pattern.finditer(code_section)
    found_matches = False
    for match in matches:
        found_matches = True
        filepath = match.group("filepath").strip()
        content = match.group("content").strip()

        # Basic sanitization for filepath (e.g. remove surrounding quotes if any)
        if filepath.startswith('"') and filepath.endswith('"'):
            filepath = filepath[1:-1]
        if filepath.startswith("'") and filepath.endswith("'"):
            filepath = filepath[1:-1]

        file_changes[filepath] = content
        logger.debug(f"Parsed file: '{filepath}', content length: {len(content)}")

    if not found_matches and code_section: # If there was a code_section but no matches
        logger.warning(f"Could not parse any structured file changes from the LLM output's code section despite markers being present. The code section started with: {code_section[:200]}")
        # This might happen if the ``` block formatting is off.
        # Return the explanation, but empty changes.
        return explanation, {}


    if not explanation and not file_changes:
        logger.error("Failed to parse both explanation and file changes from LLM output.")
        return None, None

    logger.info(f"Successfully parsed LLM solution. Explanation length: {len(explanation)}. Files found: {len(file_changes)}")
    return explanation, file_changes


def process_issue(
    issue: ScrapedIssue,
    github_handler: GitHubHandler,
    llm_handler: LLMHandler,
    config: Dict[str, Any]
) -> bool:
    """
    Processes a single scraped issue: fetches details, generates a solution,
    creates a branch, commits changes, and creates a pull request.

    Args:
        issue: The ScrapedIssue object.
        github_handler: Initialized GitHubHandler for the issue's repository.
        llm_handler: Initialized LLMHandler.
        config: Dictionary containing configuration like PR templates, branch prefixes.

    Returns:
        True if processing was successful (PR created), False otherwise.
    """
    logger.info(f"Processing issue ID: {issue.id}, Title: {issue.title}, Repo: {github_handler.full_repo_name}, Issue #: {issue.issue_number}")

    # 1. Fetch Issue Details & Context
    logger.debug(f"Fetching details for issue #{issue.issue_number} from GitHub.")
    gh_issue_details = github_handler.get_issue_details(issue.issue_number)
    if not gh_issue_details:
        logger.error(f"Could not fetch details for issue #{issue.issue_number} from {github_handler.full_repo_name}. Skipping.")
        return False

    # Use description_override if available, otherwise use GitHub issue body
    issue_body_for_llm = issue.description_override if issue.description_override else gh_issue_details.get("body", "")
    if not issue_body_for_llm and not issue.title: # If both are empty, LLM won't have much to go on
        logger.warning(f"Issue {issue.id} (GitHub #{issue.issue_number}) has no body or description_override. LLM results may be poor.")

    repo_files_context: Dict[str, str] = {}
    # Prioritize files from issue.relevant_files, then try a default like README.md
    files_to_fetch = issue.relevant_files if issue.relevant_files else []
    if not files_to_fetch and config.get("fetch_default_readme", True): # Add README by default if no specific files
        files_to_fetch.append("README.md") # Common default

    if files_to_fetch:
        logger.info(f"Fetching relevant files for context: {files_to_fetch}")
        for file_path in files_to_fetch:
            logger.debug(f"Fetching content for '{file_path}' from branch '{config.get('source_branch_name', 'main')}'")
            content = github_handler.get_file_content(file_path, branch_or_sha=config.get("source_branch_name", "main"))
            if content is not None:
                repo_files_context[file_path] = content
                logger.debug(f"Added '{file_path}' to LLM context (length: {len(content)}).")
            else:
                logger.warning(f"Could not fetch content for '{file_path}'. It might not exist or an error occurred.")
    else:
        logger.info("No specific relevant files listed for issue and default fetching (e.g. README) is disabled or failed.")


    # 2. Generate Solution
    logger.info(f"Generating solution for issue {issue.id} (GitHub #{issue.issue_number}) using LLM.")
    llm_solution_text = llm_handler.generate_solution(
        issue_title=gh_issue_details.get("title", issue.title), # Prefer GitHub's title if available
        issue_body=issue_body_for_llm,
        repo_files_context=repo_files_context,
        custom_prompt_template=config.get("llm_prompt_template") # Allow overriding default prompt
    )

    if not llm_solution_text:
        logger.error(f"LLM failed to generate a solution for issue {issue.id}. Skipping.")
        return False

    # 3. Parse LLM Solution
    logger.info("Parsing LLM solution...")
    explanation, file_changes = parse_llm_solution(llm_solution_text)

    if explanation is None or file_changes is None: # Parsing failed critically
        logger.error(f"Failed to parse LLM solution for issue {issue.id}. Skipping.")
        return False

    if not file_changes:
        logger.warning(f"LLM solution for issue {issue.id} provided an explanation but no parsable file changes. Explanation: '{explanation[:200]}...' Skipping code modification steps.")
        # Potentially create an issue comment with the explanation, or just log and move on.
        # For now, we'll skip if no code changes are suggested.
        return False # Or some other handling if just an explanation is useful

    # 4. Create Branch
    branch_suffix = str(uuid.uuid4())[:4] # Short unique suffix
    new_branch_name = f"{config.get('branch_prefix', DEFAULT_BRANCH_PREFIX)}{issue.issue_number}-{branch_suffix}"
    source_branch = config.get("source_branch_name", "main")
    logger.info(f"Creating branch '{new_branch_name}' from '{source_branch}'.")

    created_branch_name = github_handler.create_branch(new_branch_name, source_branch_name=source_branch)
    if not created_branch_name:
        logger.error(f"Failed to create branch '{new_branch_name}' for issue {issue.id}. Skipping.")
        return False
    logger.info(f"Successfully created or confirmed branch: '{created_branch_name}'")

    # 5. Commit Changes
    commit_success_all = True
    commit_shas: List[str] = []
    for file_path, new_content in file_changes.items():
        commit_message = f"Fix: Apply AI suggestion for {file_path} (issue #{issue.issue_number})"
        if len(file_changes) == 1: # If only one file, use issue title in commit msg
             commit_message = f"Fix #{issue.issue_number}: {gh_issue_details.get('title', issue.title)} - modify {file_path}"

        logger.info(f"Committing changes for '{file_path}' to branch '{created_branch_name}'.")
        commit_info = github_handler.commit_changes(
            branch_name=created_branch_name,
            commit_message=commit_message,
            file_path=file_path,
            new_content=new_content
        )
        if commit_info and commit_info.get('sha'):
            logger.info(f"Successfully committed '{file_path}'. SHA: {commit_info['sha']}")
            commit_shas.append(commit_info['sha'])
        else:
            logger.error(f"Failed to commit changes for '{file_path}' on branch '{created_branch_name}'.")
            commit_success_all = False
            break # Stop if one commit fails

    if not commit_success_all or not commit_shas:
        logger.error(f"One or more commits failed for issue {issue.id} on branch '{created_branch_name}'. Pull request will not be created.")
        # Consider attempting to delete the branch if commits failed partway
        # github_handler.delete_branch(created_branch_name) # (Needs implementation in GitHubHandler)
        return False

    # 6. Create Pull Request
    pr_title = f"Fix #{issue.issue_number}: {gh_issue_details.get('title', issue.title)} (AI Generated)"
    pr_body = (
        f"Addresses issue #{issue.issue_number}.\n\n"
        f"**AI Explanation:**\n{explanation}\n\n"
        f"**Changes proposed:**\n"
        f"- Modified/Created file(s): {', '.join(file_changes.keys())}\n"
        f"{config.get('pr_disclaimer', DEFAULT_PR_DISCLAIMER)}"
    )

    logger.info(f"Creating pull request: '{pr_title}' from '{created_branch_name}' to '{source_branch}'.")
    pr_details = github_handler.create_pull_request(
        title=pr_title,
        body=pr_body,
        head_branch=created_branch_name,
        base_branch=source_branch
    )

    if pr_details and pr_details.get("html_url"):
        logger.info(f"Successfully created pull request for issue {issue.id}: {pr_details['html_url']}")
        return True
    else:
        logger.error(f"Failed to create pull request for issue {issue.id} from branch '{created_branch_name}'.")
        return False


def run_automation(config_file_path: Optional[str] = None) -> None:
    """
    Main entry point for the automation process.
    Loads configuration, initializes handlers, loads issues, and processes each one.

    Args:
        config_file_path: Path to the .env file. If None, attempts to load '.env' from project root.
    """
    # Determine project root for consistent .env loading
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if config_file_path:
        if not os.path.isabs(config_file_path):
             actual_config_path = os.path.join(project_root, config_file_path)
        else:
            actual_config_path = config_file_path
    else:
        actual_config_path = os.path.join(project_root, ".env")

    logger.info(f"Loading configuration from: {actual_config_path}")
    if load_dotenv(dotenv_path=actual_config_path):
        logger.info("Successfully loaded .env file.")
    else:
        logger.warning(f".env file not found at {actual_config_path} or is empty. Relying on pre-set environment variables.")

    # Load configuration from environment variables
    config: Dict[str, Any] = {
        "github_token": os.getenv("GITHUB_TOKEN"),
        "openai_api_key": os.getenv("OPENAI_API_KEY"),
        "log_level": os.getenv("LOG_LEVEL", "INFO").upper(), # Logger is already set up by logger_config.py at import time
        "issues_file_path": os.getenv("ISSUES_FILE_PATH", os.path.join(project_root, DEFAULT_ISSUES_FILE_PATH)),
        "llm_model_name": os.getenv("LLM_MODEL_NAME", "gpt-3.5-turbo"),
        "llm_prompt_template": os.getenv("LLM_PROMPT_TEMPLATE_STRING") or DEFAULT_PROMPT_TEMPLATE, # Allow full prompt override
        "branch_prefix": os.getenv("BRANCH_PREFIX", DEFAULT_BRANCH_PREFIX),
        "source_branch_name": os.getenv("SOURCE_BRANCH_NAME", "main"), # Branch to base new branches off, and target for PRs
        "pr_disclaimer": os.getenv("PR_DISCLAIMER", DEFAULT_PR_DISCLAIMER),
        "fetch_default_readme": os.getenv("FETCH_DEFAULT_README", "true").lower() == "true",
    }

    # Validate essential configuration
    if not config["github_token"]:
        logger.critical("GITHUB_TOKEN not found in environment. Cannot proceed.")
        raise ValueError("GITHUB_TOKEN is not set.")
    if not config["openai_api_key"]:
        logger.critical("OPENAI_API_KEY not found in environment. Cannot proceed.")
        raise ValueError("OPENAI_API_KEY is not set.")

    # Initialize LLM Handler (once)
    try:
        llm_handler = LLMHandler(api_key=config["openai_api_key"], model_name=config["llm_model_name"])
    except (ValueError, ConnectionError) as e:
        logger.critical(f"Failed to initialize LLMHandler: {e}. Automation cannot continue.")
        return

    # Load Issues
    logger.info(f"Loading issues from: {config['issues_file_path']}")
    issues_to_process = load_issues_from_file(config["issues_file_path"])
    if not issues_to_process:
        logger.warning("No issues loaded. Automation will exit.")
        return

    logger.info(f"Found {len(issues_to_process)} issues to process.")
    successful_prs = 0
    failed_issues = 0

    # Process Each Issue
    for issue_item in issues_to_process:
        logger.info(f"--- Starting processing for issue ID: {issue_item.id} ---")
        owner_name_tuple = issue_item.repo_owner_name
        if not owner_name_tuple:
            logger.error(f"Issue ID {issue_item.id} has invalid GitHub URL: {issue_item.github_repo_url}. Skipping.")
            failed_issues += 1
            continue

        repo_owner, repo_name = owner_name_tuple

        try:
            # Initialize GitHub Handler (per issue, as it's repo-specific)
            github_handler = GitHubHandler(
                token=config["github_token"],
                repo_owner=repo_owner,
                repo_name=repo_name
            )

            if process_issue(issue_item, github_handler, llm_handler, config):
                successful_prs += 1
            else:
                failed_issues +=1
                logger.error(f"Failed to process issue ID: {issue_item.id} for repo {repo_owner}/{repo_name}.")

        except ConnectionError as e: # From GitHubHandler init mostly
            logger.error(f"Connection error setting up GitHubHandler for {repo_owner}/{repo_name} (Issue ID {issue_item.id}): {e}. Skipping this issue.")
            failed_issues += 1
        except ValueError as e: # From GitHubHandler init
             logger.error(f"Configuration error setting up GitHubHandler for {repo_owner}/{repo_name} (Issue ID {issue_item.id}): {e}. Skipping this issue.")
             failed_issues += 1
        except Exception as e:
            logger.exception(f"An unexpected critical error occurred while processing issue ID {issue_item.id} for repo {repo_owner}/{repo_name}: {e}. Skipping this issue.")
            failed_issues += 1

        logger.info(f"--- Finished processing for issue ID: {issue_item.id} ---")


    logger.info(f"Automation run completed. {successful_prs} PR(s) created successfully. {failed_issues} issue(s) failed or were skipped.")

if __name__ == "__main__":
    # This allows running the core automation directly, e.g., for development or simple cron jobs.
    # The main.py in the project root will be the primary entry point for a more structured execution.
    print("Running core automation directly...")
    logger.info("Core automation invoked directly via if __name__ == '__main__'.")
    run_automation()
    print("Core automation finished.")
